# -*- coding: utf-8 -*-
"""sth wow

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMB9ogA4TDSdH9lwrmFqSyC9LmhqAS0I
"""

# First, ensure ipywidgets is installed
!pip install ipywidgets

import ipywidgets as widgets
from IPython.display import display, HTML
import random

# List of cute affirmations
affirmations = [
    "You are amazing! 🌟",
    "You light up the world! 💖",
    "You make life sweeter! 🍭",
    "You are loved! 💕",
    "You bring joy wherever you go! ☀️"
]

# Create a button and a label
button = widgets.Button(description='❤️', button_style='success', layout=widgets.Layout(width='100px', height='100px'))
output = widgets.Output()

# Define the button click event
def on_button_click(b):
    with output:
        output.clear_output()
        print(random.choice(affirmations))
        print("You clicked the heart! 💖")

# Link the button click event to the function
button.on_click(on_button_click)

# Create a full-screen style
style = """
<style>
    .widget-button {
        font-size: 48px;
        width: 100px;
        height: 100px;
        display: block;
        margin: 0 auto;
        margin-top: 20%;
    }
    .output_area {
        text-align: center;
        font-size: 24px;
        padding: 20px;
        background-color: #ffb3e6;
        border-radius: 15px;
        margin: 20px auto;
        width: 80%;
        max-width: 600px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
    }
</style>
"""

# Display the styled elements
display(HTML(style))
display(button, output)

# prompt: full screen gui affirmation text

import ipywidgets as widgets
from IPython.display import display, HTML
import random

# List of cute affirmations
affirmations = [
" ily",
    "oooh studyy! 💖",
    "ya taybaa 🍭",
    "ily 💕",
    "yum"
]

# Create a button and a label
button = widgets.Button(description='❤️', button_style='success', layout=widgets.Layout(width='100px', height='100px'))
output = widgets.Output()

# Define the button click event
def on_button_click(b):
    with output:
        output.clear_output()
        print(random.choice(affirmations))
        print("you clicked the heart!")

# Link the button click event to the function
button.on_click(on_button_click)

# Create a full-screen style
style = """
<style>
    body {
        margin: 0; /* Remove default body margin */
        overflow: hidden; /* Hide scrollbars */
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh; /* Ensure full viewport height */
        background-color: #605678; /* Light background color */
    }
    .widget-button {
        font-size: 48px;
        width: 150px; /* Increased button size */
        height: 150px; /* Increased button size */
    }

    .output_area {
        text-align: center;
        font-size: 24px;
        padding: 20px;
        background-color: #605678859F3D; /* Light pink background */
        border-radius: 15px;
        margin: 20px auto;
        width: 80%;
        max-width: 600px;
        box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        position: absolute; /* Position the output area */
        top: 50%; /* Center vertically */
        left: 50%; /* Center horizontally */
        transform: translate(-50%, -50%); /* Adjust positioning */

    }
</style>
"""

# Display the styled elements
display(HTML(style))
display(button, output)

